export const USER_SHOW_LOADING = "SHOW LOADING FOR USER"
export const USER_HIDE_LOADING = "HIDE LOADING FOR USER"
export const LANDING_PAGE_GET_DATA_SUCESS = "LANDIGN PAGE GET DATA SUCESSSFULL"
export const LANDING_PAGE_ERROR = "LANDING PAGE ERROR"
